### ISSUE TITLE
`aia_requests.build_aia_urls` struggles with querying short time intervals.

### ISSUE THREAD

**Issue by masek014** [masek014/aia_lightcurves#8]
# Problem

Sometimes, `aia_requests.parse_file_ids` keys a `NoneType` object (resulting in an exception) when the time interval provided to `build_aia_urls` is relatively short (< 5 minutes). I do not know what is causing this, and I do not know why it only occurs for short time intervals. However, I have noticed that this issue is not consistent, meaning it's likely not a problem with the relevant functions in `aia_requests` and rather is an issue with the server being queried.

# Solution

Since this is not a consistent problem, it can be mitigated by attempting the query again if it fails. It will eventually succeed by adding a while loop to attempt the query again when it fails.

Will commit a solution later today.

**Comment by settwi** [comment]
thanks reedOn May 4, 2023, at 09:25, Reed B. Masek ***@***.***> wrote:﻿
Problem
Sometimes, aia_requests.parse_file_ids keys a NoneType object (resulting in an exception) when the time interval provided to build_aia_urls is relatively short (< 5 minutes). I do not know what is causing this, and I do not know why it only occurs for short time intervals. However, I have noticed that this issue is not consistent, meaning it's likely not a problem with the relevant functions in aia_requests and rather is an issue with the server being queried.
Solution
Since this is not a consistent problem, it can be mitigated by attempting the query again if it fails. It will eventually succeed by adding a while loop to attempt the query again when it fails.
Will commit a solution later today.

**Comment by masek014** [comment]
Stop checking your email - you're on vacation.

**Comment by settwi** [comment]
>:(On May 4, 2023, at 09:43, Reed B. Masek ***@***.***> wrote:﻿
Stop checking your email - you're on vacation.

**Comment by masek014** [comment]
[Fixed with commit](https://github.com/masek014/aia_lightcurves/commit/44eeba9d87f0f6af86b616608509c35668e3051b), although the implementation of the fix could maybe be improved.
